name: Build Test Pack Push Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  packages: write
          
jobs:
    build-test-pack-push:
      uses: ./.github/workflows/build-test-pack-push.yml
      if: github.ref_type == 'tag'
    
    push-release:
      runs-on: ubuntu-latest
      needs: [ build-test-pack-push ]
      if: github.ref_type == 'tag'
      steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true